name: Update gist
on:
  workflow_dispatch:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 6bb91b453fe3c2a5cff55a32f42b770b
          TIMEZONE: Asia/Seoul
